### PR TITLE
Added it-IT section

### PR DESCRIPTION
**Pull request by danielecampione**

### CODE REVIEW

**Comment by fasheng** [comment]
Hi, thanks for your PR. I'm not the author of the project, but you'd better merge your commits to one, just like this:

```
git rebase -i c223d79~1
# then use squash or fixup method for each commit but the first one
git push --force <your github fork>
```

Thanks~

**Comment by danielecampione** [comment]
Hi @fasheng, thanks.
Please can you tell me your e-mail address? I've some questions for you (I am a beginner in git).

**Comment by fasheng** [comment]
It's xufasheng@linuxdeepin.com
And discussing git here is doesn't matter, too ;)

**Comment by danielecampione** [comment]
Thanks @fasheng, now I write an e-mail to you.
Thanks for your support.

**Pull request closed without merging**
